// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0PuxzT7WoaTzktov-1eh_hFARZvDYJJA',
    appId: '1:503468321775:web:d9f78a9cddf686bfcd241a',
    messagingSenderId: '503468321775',
    projectId: 'game-stats-270718',
    authDomain: 'game-stats-270718.firebaseapp.com',
    storageBucket: 'game-stats-270718.appspot.com',
    measurementId: 'G-G5EJCDRTRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_pHd_6q_OyvBZfMFbdCxjua9tI6hzJpc',
    appId: '1:503468321775:android:3564ba6b0377b079cd241a',
    messagingSenderId: '503468321775',
    projectId: 'game-stats-270718',
    storageBucket: 'game-stats-270718.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7LlLznrf3TTuajOSAfJgHdWItp6iu8dw',
    appId: '1:503468321775:ios:1be32c61ae56b957cd241a',
    messagingSenderId: '503468321775',
    projectId: 'game-stats-270718',
    storageBucket: 'game-stats-270718.appspot.com',
    iosClientId: '503468321775-2ttjtcfqlq99vmfegrmod5uitn7ivb95.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameStats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7LlLznrf3TTuajOSAfJgHdWItp6iu8dw',
    appId: '1:503468321775:ios:54a4027d330f34aacd241a',
    messagingSenderId: '503468321775',
    projectId: 'game-stats-270718',
    storageBucket: 'game-stats-270718.appspot.com',
    iosClientId: '503468321775-tbjtvj3pdet459tc0mp9lnp3oo42njpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameStats.RunnerTests',
  );
}
